// Code generated by sqlc. DO NOT EDIT.
// versions:
// sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryAggregation = `-- name: CategoryAggregation :many
SELECT
 p.category,
 COUNT(DISTINCT p.id) AS product_count,
 COUNT(oi.id) AS sold_items,
 COALESCE(SUM(oi.quantity), 0)::bigint AS total_quantity,
 COALESCE(AVG(p.price), 0)::numeric AS avg_price,
 COALESCE(SUM(oi.quantity * oi.price), 0)::numeric AS revenue
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.id
GROUP BY p.category
ORDER BY revenue DESC
`

type CategoryAggregationRow struct {
	Category      string         `json:"category"`
	ProductCount  int64          `json:"product_count"`
	SoldItems     int64          `json:"sold_items"`
	TotalQuantity int64          `json:"total_quantity"`
	AvgPrice      pgtype.Numeric `json:"avg_price"`
	Revenue       pgtype.Numeric `json:"revenue"`
}

func (q *Queries) CategoryAggregation(ctx context.Context) ([]CategoryAggregationRow, error) {
	rows, err := q.db.Query(ctx, categoryAggregation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryAggregationRow{}
	for rows.Next() {
		var i CategoryAggregationRow
		if err := rows.Scan(
			&i.Category,
			&i.ProductCount,
			&i.SoldItems,
			&i.TotalQuantity,
			&i.AvgPrice,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderComplex = `-- name: GetOrderComplex :one
SELECT
 o.id AS order_id,
 o.customer_id,
 o.total,
 COUNT(oi.id) AS item_count,
 SUM(oi.quantity) AS total_quantity,
 MAX(oi.price)::float8 AS max_item_price,
 MIN(oi.price)::float8 AS min_item_price,
 AVG(oi.quantity * oi.price)::float8 AS avg_line_value
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id
WHERE o.id = $1
GROUP BY o.id, o.customer_id, o.total
`

type GetOrderComplexRow struct {
	OrderID       int64          `json:"order_id"`
	CustomerID    int64          `json:"customer_id"`
	Total         pgtype.Numeric `json:"total"`
	ItemCount     int64          `json:"item_count"`
	TotalQuantity int64          `json:"total_quantity"`
	MaxItemPrice  float64        `json:"max_item_price"`
	MinItemPrice  float64        `json:"min_item_price"`
	AvgLineValue  float64        `json:"avg_line_value"`
}

func (q *Queries) GetOrderComplex(ctx context.Context, id int64) (GetOrderComplexRow, error) {
	row := q.db.QueryRow(ctx, getOrderComplex, id)
	var i GetOrderComplexRow
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.Total,
		&i.ItemCount,
		&i.TotalQuantity,
		&i.MaxItemPrice,
		&i.MinItemPrice,
		&i.AvgLineValue,
	)
	return i, err
}

const getOrderItemsWithProducts = `-- name: GetOrderItemsWithProducts :many
SELECT
 oi.id,
 oi.quantity,
 oi.price,
 p.id AS product_id,
 p.name AS product_name,
 p.category
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type GetOrderItemsWithProductsRow struct {
	ID          int64          `json:"id"`
	Quantity    int32          `json:"quantity"`
	Price       pgtype.Numeric `json:"price"`
	ProductID   int64          `json:"product_id"`
	ProductName string         `json:"product_name"`
	Category    string         `json:"category"`
}

func (q *Queries) GetOrderItemsWithProducts(ctx context.Context, orderID int64) ([]GetOrderItemsWithProductsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsWithProducts, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderItemsWithProductsRow{}
	for rows.Next() {
		var i GetOrderItemsWithProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.Price,
			&i.ProductID,
			&i.ProductName,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
