// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderSummary = `-- name: GetOrderSummary :one
SELECT
    o.id,
    o.customer_id,
    COALESCE(SUM(oi.quantity * oi.price), 0)::numeric AS total
FROM orders o
LEFT JOIN order_items oi
    ON oi.order_id = o.id
WHERE o.id = $1
GROUP BY o.id, o.customer_id
`

type GetOrderSummaryRow struct {
	ID         int64          `json:"id"`
	CustomerID int64          `json:"customer_id"`
	Total      pgtype.Numeric `json:"total"`
}

func (q *Queries) GetOrderSummary(ctx context.Context, id int64) (GetOrderSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOrderSummary, id)
	var i GetOrderSummaryRow
	err := row.Scan(&i.ID, &i.CustomerID, &i.Total)
	return i, err
}

const listOrderSummaries = `-- name: ListOrderSummaries :many
SELECT
    o.id,
    o.customer_id,
    COALESCE(SUM(oi.quantity * oi.price), 0)::numeric AS total
FROM orders o
LEFT JOIN order_items oi
    ON oi.order_id = o.id
GROUP BY o.id, o.customer_id
ORDER BY o.id
LIMIT $1
OFFSET $2
`

type ListOrderSummariesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrderSummariesRow struct {
	ID         int64          `json:"id"`
	CustomerID int64          `json:"customer_id"`
	Total      pgtype.Numeric `json:"total"`
}

func (q *Queries) ListOrderSummaries(ctx context.Context, arg ListOrderSummariesParams) ([]ListOrderSummariesRow, error) {
	rows, err := q.db.Query(ctx, listOrderSummaries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderSummariesRow{}
	for rows.Next() {
		var i ListOrderSummariesRow
		if err := rows.Scan(&i.ID, &i.CustomerID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
